### PR TITLE
Feature#2 project setup

### LINKED ISSUE #2: Project setup
# REQUIREMENTS
Create the project and sync with repository

# Acceptance Criteria
- [x] Init folder and run in android emulator.
- [x] Clean the template

### PR DESCRIPTION
**Pull request by hearagmu**
# Description
This is about init repository, and how you can download the default template and next to clean for start up.
  
  ## Screenshots 

image
image
Check out to branch:
image
image
We make sure we are on the right branch:
image
We clean the application:
image

### CODE REVIEW

**Review by genesis9432 — APPROVED** [review]
good setup to initialize your project, good luck!

**Comment by JorgeGarciaRa** [comment]
Nice work !! 
good luck

**Review by mariam-rivera — APPROVED** [review]
Nice job!

**Review by JorgeGarciaRa — APPROVED** [review]
Good luck !!

**Pull request merged**
